<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-client-api</module>
        <module>yudao-module-client-biz</module>
    </modules>
    <artifactId>yudao-module-client</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        client 客户端工具模块：提供一些客户端工具，例如：日志捞取，打包地址等等。
    </description>

</project>
